# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SmartReplies' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SmartReplies
pod 'Firebase/Analytics'
pod 'GoogleMLKit/SmartReply'


end
